#!/usr/bin/env python3
"""Generate snapshots/v<skill_version>.yaml — a frozen record of the tool set
and versions at the current skill version, for reproducible recommendations.

The advisor stamps each plan with `skill vX.Y.Z, registry snapshot vX.Y.Z`; this
file is what that stamp points back to. Phase 3 regenerates it each release.

Usage:  python3 pipeline/snapshot.py [--date YYYY-MM-DD]
Reads the skill version from SKILL.md frontmatter (metadata.version).
"""
from __future__ import annotations

import argparse
import datetime
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SKILL = REPO / "SKILL.md"
TOOLS = REPO / "registry" / "tools"
SNAPSHOTS = REPO / "snapshots"


def skill_version() -> str:
    text = SKILL.read_text()
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise SystemExit("Could not parse SKILL.md frontmatter")
    front = yaml.safe_load(parts[1])
    version = (front.get("metadata") or {}).get("version")
    if not version:
        raise SystemExit("metadata.version missing from SKILL.md")
    return str(version)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=datetime.date.today().isoformat())
    args = ap.parse_args()

    version = skill_version()
    tools: dict[str, dict] = {}
    for path in sorted(TOOLS.glob("*.yaml")):
        data = yaml.safe_load(path.read_text())
        tools[data["id"]] = {
            "name": data.get("name"),
            "primary_category": data.get("primary_category"),
            "status": data.get("status"),
            "version": data.get("version"),
            "verified_at": data.get("verified_at"),
        }

    snapshot = {
        "snapshot": f"v{version}",
        "skill_version": version,
        "generated_at": args.date,
        "tool_count": len(tools),
        "tools": tools,
    }

    SNAPSHOTS.mkdir(exist_ok=True)
    out = SNAPSHOTS / f"v{version}.yaml"
    header = (
        "# Auto-generated by pipeline/snapshot.py — do not edit by hand.\n"
        "# Frozen tool set + versions for this skill release; plan provenance\n"
        "# stamps (skill vX.Y.Z, registry snapshot vX.Y.Z) point here.\n"
    )
    out.write_text(header + yaml.safe_dump(snapshot, sort_keys=False, allow_unicode=True))
    print(f"Wrote {out.relative_to(REPO)} ({len(tools)} tools, snapshot v{version}, generated_at {args.date}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
