#!/usr/bin/env python3
"""Validate advisor forward-test fixtures against the skill contract.

This is a lightweight contract lint, not a recommendation engine and not an LLM
test. It checks that scenario-shaped fixtures encode the hard rules in
SKILL.md, scenarios/*.md, references/*.md, and templates/plan-template.md.

Usage:
  python3 pipeline/validate_advisor_contract.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required:  pip install pyyaml")

sys.dont_write_bytecode = True
import summarize_candidates

REPO = Path(__file__).resolve().parent.parent
FIXTURES = REPO / "scenarios" / "fixtures" / "advisor-contract.yaml"
PLAN_TEMPLATE = REPO / "templates" / "plan-template.md"
SCENARIOS_DIR = REPO / "scenarios"

SCENARIO_FILES = {
    "new-project": "new-project.md",
    "brownfield-adopt": "brownfield-adopt.md",
    "brownfield-optimize": "brownfield-optimize.md",
    "quick-oneoff": "quick-oneoff.md",
}
ALL_LAYERS = set(summarize_candidates.LAYER_ORDER)
HEAVY_ONEOFF_LAYERS = {"spec", "skill", "orchestration"}
QUICK_ALLOWED_OMIT = "5. 维护姿态 / Maintenance posture"
FOOTER_MARKER = "Generated by **code-agent-toolsmith**"


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        data = yaml.safe_load(path.read_text())
    except yaml.YAMLError as exc:
        raise SystemExit(f"{path.relative_to(REPO)}: YAML parse error: {exc}") from exc
    if not isinstance(data, dict):
        raise SystemExit(f"{path.relative_to(REPO)}: top level is not a mapping")
    return data


def template_sections() -> list[str]:
    sections: list[str] = []
    for line in PLAN_TEMPLATE.read_text().splitlines():
        match = re.match(r"^##\s+(.+?)\s*$", line)
        if match:
            sections.append(match.group(1))
    if not sections:
        raise SystemExit(f"{PLAN_TEMPLATE.relative_to(REPO)}: no level-2 sections found")
    return sections


def normalize_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item) for item in value if str(item)]


def route_fixture(fixture: dict[str, Any]) -> str | None:
    """Mirror SKILL.md's coarse scenario routing for fixture data."""
    state = fixture.get("repo_state") or {}
    request = str(fixture.get("user_request") or "").lower()

    oneoff_cues = ("one-off", "one off", "throwaway", "quick", "temporary", "临时", "一次性")
    if state.get("scope") == "one_off" or any(cue in request for cue in oneoff_cues):
        return "quick-oneoff"

    if state.get("project_age") == "new":
        return "new-project"

    pain = normalize_list(state.get("pain"))
    if (
        state.get("satisfaction") == "unhappy"
        or state.get("ai_tooling") == "heavy"
        or bool(pain)
    ):
        return "brownfield-optimize"

    if state.get("project_age") == "existing" and state.get("ai_tooling") in {"none", "light"}:
        return "brownfield-adopt"

    return None


def active_layers(expected: dict[str, Any]) -> set[str]:
    layers = set(normalize_list(expected.get("recommended_layers")))
    active_tools = expected.get("active_tools_by_layer") or {}
    if isinstance(active_tools, dict):
        for layer, tools in active_tools.items():
            if normalize_list(tools):
                layers.add(str(layer))
    return layers


def check_fixture(
    fixture: dict[str, Any],
    required_sections: list[str],
    errors: list[str],
) -> None:
    fid = str(fixture.get("id") or "<missing-id>")
    scenario = str(fixture.get("scenario") or "")
    expected = fixture.get("expected") or {}

    if scenario not in SCENARIO_FILES:
        errors.append(f"{fid}: unknown scenario {scenario!r}")
    else:
        scenario_path = SCENARIOS_DIR / SCENARIO_FILES[scenario]
        if not scenario_path.exists():
            errors.append(f"{fid}: routed scenario file missing: {scenario_path.relative_to(REPO)}")

    routed = route_fixture(fixture)
    if routed != scenario:
        errors.append(f"{fid}: route_fixture -> {routed!r}, expected {scenario!r}")

    layers = active_layers(expected)
    unknown_layers = sorted(layer for layer in layers if layer not in ALL_LAYERS)
    if unknown_layers:
        errors.append(f"{fid}: unknown recommended layer(s): {', '.join(unknown_layers)}")

    active_tools = expected.get("active_tools_by_layer") or {}
    if not isinstance(active_tools, dict):
        errors.append(f"{fid}: expected.active_tools_by_layer must be a mapping")
        active_tools = {}
    for layer, tools in active_tools.items():
        tool_ids = normalize_list(tools)
        if len(tool_ids) > 1:
            errors.append(
                f"{fid}: layer {layer!r} has {len(tool_ids)} active tools; default cap is one"
            )
        if tool_ids and str(layer) not in normalize_list(expected.get("recommended_layers")):
            errors.append(f"{fid}: layer {layer!r} has active tools but is not recommended")

    controls = set(normalize_list(expected.get("required_controls")))
    spec_on = "spec" in layers or bool(normalize_list(active_tools.get("spec")))
    if spec_on and "drift-control" not in controls:
        errors.append(f"{fid}: spec layer is on but required_controls lacks drift-control")

    if scenario == "quick-oneoff":
        heavy_on = sorted(layers & HEAVY_ONEOFF_LAYERS)
        if heavy_on:
            errors.append(f"{fid}: quick-oneoff turns on heavy layer(s): {', '.join(heavy_on)}")
        forbidden = set(normalize_list(expected.get("forbidden_layers_by_default")))
        missing_forbidden = sorted(HEAVY_ONEOFF_LAYERS - forbidden)
        if missing_forbidden:
            errors.append(
                f"{fid}: quick-oneoff must forbid heavy default layer(s): "
                + ", ".join(missing_forbidden)
            )

    skeleton = expected.get("expected_skeleton") or {}
    if not isinstance(skeleton, dict):
        errors.append(f"{fid}: expected.expected_skeleton must be a mapping")
        return

    include_sections = set(normalize_list(skeleton.get("include_sections")))
    omit_sections = set(normalize_list(skeleton.get("omit_sections")))
    covered_sections = include_sections | omit_sections
    missing_sections = [section for section in required_sections if section not in covered_sections]
    if missing_sections:
        errors.append(
            f"{fid}: expected skeleton missing template section(s): "
            + "; ".join(missing_sections)
        )

    if scenario != "quick-oneoff" and omit_sections:
        errors.append(f"{fid}: only quick-oneoff may omit template sections")
    illegal_omits = sorted(section for section in omit_sections if section != QUICK_ALLOWED_OMIT)
    if illegal_omits:
        errors.append(f"{fid}: illegal omitted section(s): " + "; ".join(illegal_omits))

    footer = str(skeleton.get("footer") or "")
    if FOOTER_MARKER not in footer:
        errors.append(f"{fid}: expected skeleton footer is missing the skill provenance marker")


def check_candidate_summaries(fixtures: list[dict[str, Any]], errors: list[str]) -> None:
    tools = summarize_candidates.load_tools()
    scenarios = sorted({str(item.get("scenario") or "") for item in fixtures})
    for scenario in scenarios:
        canonical = summarize_candidates.SCENARIO_ALIASES.get(scenario)
        if not canonical:
            continue
        config = summarize_candidates.SCENARIOS[canonical]
        rendered = summarize_candidates.render_candidates(canonical, config, tools)
        if not rendered.strip():
            errors.append(f"{scenario}: summarize_candidates output is empty")
            continue
        if "## Candidates by Layer" not in rendered:
            errors.append(f"{scenario}: summarize_candidates output lacks candidate section")


def check_scenario_coverage(fixtures: list[dict[str, Any]], errors: list[str]) -> None:
    scenarios = {str(item.get("scenario") or "") for item in fixtures if isinstance(item, dict)}
    missing = sorted(set(SCENARIO_FILES) - scenarios)
    if missing:
        errors.append("fixtures missing required scenario(s): " + ", ".join(missing))


def main() -> int:
    data = load_yaml(FIXTURES)
    fixtures = data.get("fixtures")
    if not isinstance(fixtures, list) or not fixtures:
        raise SystemExit(f"{FIXTURES.relative_to(REPO)}: fixtures must be a non-empty list")

    errors: list[str] = []
    seen_ids: set[str] = set()
    required_sections = template_sections()

    for fixture in fixtures:
        if not isinstance(fixture, dict):
            errors.append("fixtures: every item must be a mapping")
            continue
        fid = str(fixture.get("id") or "")
        if not fid:
            errors.append("fixtures: item missing id")
        elif fid in seen_ids:
            errors.append(f"{fid}: duplicate fixture id")
        seen_ids.add(fid)
        check_fixture(fixture, required_sections, errors)

    check_scenario_coverage(fixtures, errors)
    check_candidate_summaries(fixtures, errors)

    if errors:
        print("Advisor contract validation failed:")
        for error in errors:
            print(f"  - {error}")
        return 1

    scenario_count = len({fixture["scenario"] for fixture in fixtures})
    print(
        f"Validated {len(fixtures)} advisor fixture(s) across "
        f"{scenario_count} scenario(s)."
    )
    print(
        "All checks passed: routing, quick-oneoff restraint, drift-control, "
        "one-tool-per-layer, template skeletons, candidate summaries."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
